#!/bin/bash

set -euo pipefail

nextflow run main.nf \
  --sample_list /lustre/scratch127/cellgen/cellgeni/cakirb/nf-larry/samples_kit.json \
  --fastqs_path /lustre/scratch126/cellgen/team298/projects/larry/kittest_data/fastqs/larry \
  --gex_path /lustre/scratch126/cellgen/team298/projects/larry/larry5_GEX/objects \
  --project_tag kittest \
  --plot_cumulative true \
  --ansi-log false \
  -resume