#!/bin/bash

set -euo pipefail

nextflow run cellgeni/nf-larry -r main\
  -entry all \
  --fastqs_path /lustre/scratch127/cellgen/cellgeni/bc8/larry/fastqs \
  --sample_csv /lustre/scratch127/cellgen/cellgeni/bc8/_repos/nf-larry/examples/samples_larry_b3_v2.csv \
  --gex_path /lustre/scratch127/cellgen/cellgeni/bc8/larry/starsolo-results \
  --project_tag test \
  --plot_cumulative true \
  --ansi-log false \
  -resume