#!/bin/bash

set -euo pipefail

nextflow run main.nf \
  -entry after_first \
  --sample_json /lustre/scratch127/cellgen/cellgeni/cakirb/nf-larry/samples_kit.json \
  --barm_csv /lustre/scratch127/cellgen/cellgeni/cakirb/nf-larry/barm.csv \
  --gex_path /lustre/scratch126/cellgen/team298/projects/larry/larry5_GEX/objects \
  --project_tag kittest4 \
  --make_pdf false \
  --plot_cumulative false \
  --ansi-log false \
  -resume
