#!/bin/bash

set -euo pipefail

nextflow run cellgeni/nf-larry -r main \
  -entry from_qc \
  --sample_csv /lustre/scratch127/cellgen/cellgeni/bc8/_repos/nf-larry/examples/samples_larry_b3_v2.csv \
  --barm_csv /lustre/scratch127/cellgen/cellgeni/cakirb/nf-larry/barm.csv \
  --gex_path /lustre/scratch127/cellgen/cellgeni/bc8/larry/starsolo-results \
  --project_tag test \
  --make_pdf false \
  --plot_cumulative false \
  --ansi-log false \
  -resume
